Output create-milestone-draft.gif
Set FontSize 14
Set Width 800
Set Height 600

# Run
Type "cyclestone"
Sleep 500ms
Enter

# Init
# Sleep 500ms
# Down
# Sleep 50ms
# Down
# Sleep 50ms
# Down
# Sleep 50ms
# Down
# Sleep 250ms
# Enter

# Main (1)
Sleep 1750ms
Type "c"

# Create
Sleep 500ms
Type "Setup a base go project"
Sleep 1000ms
Tab
Sleep 250ms
Tab
Sleep 250ms
Tab
Sleep 250ms
Tab
Sleep 250ms
Enter
Sleep 2000ms

